### ISSUE TITLE
Inbility to resolve parsed EDN symbol when upgrading to 1.0.0-beta1

### ISSUE THREAD

**Issue by billtuba** [taoensso/tempel#6] opened 2024-02-16 21:52 UTC
Description
----
When upgrading to `1.0.0-beta1` ( from `1.0.0-alpha1`) I noticed if I pass JVM arg
`-Dtaoesnsso.timbre.config.edn=some-symbol` - `some-symbol` is not being evaluated.

Steps to reproduce
----
[Gist](https://gist.github.com/billtuba/4c2a1c4639dc16e43fdf24966542072b)  
(its a clj tools project)

OS/Java version
----
Description:	Ubuntu 22.04.3 LTS
Release:	22.04 

openjdk version "17" 2021-09-14
OpenJDK Runtime Environment Temurin-17+35 (build 17+35)
OpenJDK 64-Bit Server VM Temurin-17+35 (build 17+35, mixed mode, sharing)

Notes
----
If I do a diff on the dependency trees  (`alpha`  vs `beta`) I get : 
```
< com.taoensso/tempel 1.0.0-alpha1
<   . com.taoensso/encore 3.74.0
<     . org.clojure/tools.reader 1.3.6
---
> com.taoensso/tempel 1.0.0-beta1
>   . com.taoensso/encore 3.76.0
>     . org.clojure/tools.reader 1.3.7
```
 
In `encore` between `3.74.0` and `3.76.0` I noticed [this](https://github.com/taoensso/encore/commit/cac3c37ce77a9e18cb79f433fd4acb5ff5355a59) .

It looks like the feature that resolves  [edn](https://github.com/taoensso/encore/commit/cac3c37ce77a9e18cb79f433fd4acb5ff5355a59#diff-97d1ee6e79f1ceb020e49665fd3aa43c41548d019842da7d63441e182869e649L5037) symbols was [removed](https://github.com/taoensso/encore/commit/cac3c37ce77a9e18cb79f433fd4acb5ff5355a59#diff-97d1ee6e79f1ceb020e49665fd3aa43c41548d019842da7d63441e182869e649R5068) ? 

Is the feature deprecated or is there another way to achieve the same effect?

I didn't know if I should file this ticket here or not. Thanks!

**Comment by ptaoussanis** [comment] 2024-02-17 13:25
@billtuba 

Hi Bill, thanks for pinging about this - and for the excellent+clear report 👍 Helped make it much easier to investigate 🙏

The behaviour you're seeing was indeed an unintended regression, really sorry about the trouble! I've been doing a lot of work on Encore's config API recently, haven't gotten around to updating Timbre yet, and I missed this particular backwards-compatibility case.

Have just pushed a fix to Encore. Your test project now works okay on my end when including the latest version (`{com.taoensso/encore {:mvn/version "3.80.0"}}`).

But please ping if you still have any more trouble.

Happy weekend, cheers! :-)

**Comment by billtuba** [comment] 2024-02-23 17:44
We used the new encore lib, our current timbre and the beta1-tempel...

Works perfectly!! Thanks @ptaoussanis for the quick turnaround. Sorry it took me so long to get back to you to confirm.

**Comment by ptaoussanis** [comment] 2024-02-23 17:46
No worries, thanks for the confirmation 👍 Happy weekend, cheers :-)

**Closed as completed by ptaoussanis** 2024-02-23 17:46 UTC
Labels: bug
